Bonsai.Sgen/Program.cs
Directory.Build.props

This PR fixes the case of required collection types where the instance of the array was set to `Collection` instead of `List` to match the property and field types.
Fixes #3

Ensure consistent array instance type

---

Bonsai.Sgen/Program.cs

Prefer required option instead of option with default value to make tool display built-in help output when no arguments are provided.

Make schema option required

---

Bonsai.Sgen.Tests/Bonsai.Sgen.Tests.csproj
Bonsai.Sgen.Tests/EnumGenerationTests.cs
Bonsai.Sgen.Tests/TestHelper.cs
Bonsai.Sgen.sln
Bonsai.Sgen/Bonsai.Sgen.csproj
Bonsai.Sgen/CSharpCodeDomGeneratorSettings.cs
Bonsai.Sgen/Program.cs
Bonsai.Sgen/Properties/AssemblyInfo.cs
Directory.Build.props

A unit test project is added so we can track regressions and evaluate desired results when implementing more complex code generator features. Minor code refactoring was made to make testing easier and more consistent, and a simple enum generation regression test was added as example.

Add unit test project

---

Bonsai.Sgen/CSharpClassTemplate.cs

This PR improves class generation for schemas declaring inherited properties from subschemas, e.g. using the `allOf` keyword. Essentially any pattern recognized by NJsonSchema to give rise to a base class inheritance relationship will be captured. A protected copy constructor method is generated for each type, to allow initialization of base class fields.
Support for abstract base classes is also provided using extensions such as the `x-abstract` properties, which are natively supported by NJsonSchema. In this case the combinator constructor methods are removed from the class, since it is never possible to create an instance from an abstract class.

Add support for inherited class properties

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen/CSharpClassTemplate.cs
Bonsai.Sgen/CSharpCodeDomGenerator.cs
Bonsai.Sgen/CSharpSerializerTemplate.cs

This PR extends class generation to support OpenAPI-style type discriminators.
This pattern is recognized by NJsonSchema, and its code generation framework already provides templates for implementing a `JsonInheritanceConverter` class and `JsonInheritanceAttribute` which can be used to annotate generated classes with arbitrary discriminator properties and type mappings.
A simple unit test for polymorphic deserialization of a discriminated type is provided.

Add support for JSON type discriminators

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen/Bonsai.Sgen.csproj
Bonsai.Sgen/CSharpClassTemplate.cs
Bonsai.Sgen/CSharpCodeDomGenerator.cs
Bonsai.Sgen/CSharpYamlDiscriminatorTemplate.cs
Bonsai.Sgen/CSharpYamlDiscriminatorTypeInspectorTemplate.cs
Bonsai.Sgen/CSharpYamlSerializerTemplate.cs

This PR extends class generation to support OpenAPI-style type discriminators for the YAML serializer.
YamlDotNet has recently provided built-in support for type discriminators. Unfortunately the built-in classes do not support the specified discriminator property to be "hidden" in the model types in the same way that NJsonSchema code generation implements for JSON.Net.
Fortunately, it was possible to remedy this by using the type inspector classes to provide the missing discriminator properties.
Fixes #7

Add support for YAML type discriminators

---

Bonsai.Sgen/CSharpClassTemplate.cs

This PR extends constructor support by providing generic overloads for instantiating new data type values from any source sequence. In combination with the `InputMapping` operator, this will make it easier and more efficient to perform dynamic parameterization of constructed values.

Allow constructing values from any source sequence

---

Bonsai.Sgen.Tests/ToStringGenerationTests.cs
Bonsai.Sgen/CSharpClassTemplate.cs

Inspired by C# [record type formatting for display](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record#built-in-formatting-for-display), this PR introduces automatic generation of a `ToString` and a virtual `PrintMembers` method.
Various edge cases were captured for different combinations of derived types and empty types and a compiler unit test was added as a simple regression test to ensure the validity of generated code.
Fixes #10

Generate ToString override with member formatting

---

Bonsai.Sgen.Tests/EnumGenerationTests.cs
Bonsai.Sgen/CSharpEnumTemplate.cs

This PR ensures that `StringEnumConverter` is used for all string types constrained by `enum` in the JSON schema. This makes serialization consistent between YAML and JSON and ensures all allowed values are written as their original strings back to JSON.
Fixes #11

Use StringEnumConverter for string enum types

---

Bonsai.Sgen/Bonsai.Sgen.csproj
Bonsai.Sgen/CSharpCodeDomTemplate.cs
README.md

This PR ensures that auto-generated version strings include all configured serializer libraries and their corresponding versions used by the generator. This is useful for provenance tracking and to help extension authors include the correct serializer dependencies in their project files.

Generate serializer library provenance

---

Bonsai.Sgen/CSharpClassCodeArtifact.cs
Bonsai.Sgen/CSharpCodeDomGenerator.cs
Bonsai.Sgen/CSharpTypeMatchTemplate.cs

This PR automatically generates type matching operators for discriminated union types. This will allow easier handling of polymorphic types by simultaneously filtering and casting sequences of base types.
The current implementation generates a single type matching operator for each base type declaring a discriminator property. A type mapping property is provided to select the concrete target type. Available property values are taken from the list of derived types extracted from the input schema.

Generate type matching operator for derived types

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen.Tests/TestHelper.cs
Bonsai.Sgen/CSharpTypeResolver.cs
Bonsai.Sgen/JsonSchemaExtensions.cs
Bonsai.Sgen/Program.cs

This PR adds preliminary support for validation and code generation of `oneOf` inheritance patterns where discriminated unions are used to define polymorphic properties or arrays. In this case, it is common to use a `oneOf` restriction to specify the exact set of allowed types.
NJsonSchema does not directly support this yet (see https://github.com/RicoSuter/NJsonSchema/issues/13), but the approach detailed here works for some of the most common cases. Supporting this pattern will allow code completion of polymorphic types (with discriminator validation) for manually edited YAML / JSON files.
An example of a supported schema is below:
```json
{
"$schema": "http://json-schema.org/draft-04/schema#",
"type": "object",
"title": "Container",
"properties": {
"Animals": {
"type": "array", …
```

Add support for oneOf inheritance

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen/CSharpCodeDomGenerator.cs
Bonsai.Sgen/JsonSchemaExtensions.cs
Bonsai.Sgen/SerializerLibraries.cs

This PR fixes one edge case with discriminator code generation where the reused `JsonInheritanceAttribute` was not being automatically generated due to missing declaration of `JsonConverterAttribute`, when YAML-only libraries were selected.
Parametric regression testing was added to ensure all serializer library combinations are included in the tests.

Ensure inheritance attribute is generated

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen/JsonSchemaExtensions.cs

Pydantic exported schemas do not commonly support `allOf` inheritance (see https://github.com/pydantic/pydantic/issues/478) and regularly emit inline property schemas comprised of a `discriminator` with custom mappings and a `oneOf` constraint.
Following support for `oneOf` introduced in #23 this PR extends this support to inline discriminated schema properties by converting the original schema into an inheritance tree using `allOf`.
The main current limitation is for definitions participating in multiple distinct discriminated unions: in this case the first discriminator will be used as the root of the inheritance and no multiple inheritance is allowed.
Fixes #25

Support inline oneOf discriminated properties

---

Bonsai.Sgen.Tests/CasingGenerationTests.cs
Bonsai.Sgen/CSharpCodeDomGeneratorSettings.cs
Bonsai.Sgen/CSharpEnumNameGenerator.cs
Bonsai.Sgen/CSharpPropertyNameGenerator.cs
Bonsai.Sgen/CSharpTypeNameGenerator.cs

NJsonSchema supports implementing name generator interfaces to control more specifically how the names for different entities are generated. This PR overrides the default name generators from NJsonSchema with the `PascalNamingConvention` implementation from YamlDotNet which supports full hyphen-case and snake_case conversions.
Fixes #26

Add name generators for property type and enum

---

Bonsai.Sgen.Tests/CasingGenerationTests.cs
Bonsai.Sgen/CSharpEnumNameGenerator.cs
Bonsai.Sgen/CSharpNamingConvention.cs
Bonsai.Sgen/CSharpPropertyNameGenerator.cs
Bonsai.Sgen/CSharpTypeNameGenerator.cs

This PR fixes a few naming convention edge cases. Regression tests are added to make it easier to debug future naming convention issues.
Fixes #29

Fix naming convention edge cases

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen/JsonSchemaExtensions.cs

This PR ensures a fallback for the edge case where the schema defining array items is itself an anonymous discriminator. This is not supported nor recommended, but we want to leave a fallback to make it possible to inspect the output.

Fallback for anonymous array item discriminators

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen.Tests/SchemaTestHelper.cs
Bonsai.Sgen/JsonSchemaExtensions.cs

This PR ensures that `oneOf` inheritance is resolved into `allOf` inheritance both for inline and reference schemas. Unit tests were refactored to test a wider range of discriminator patterns, including both single property and collections. Type name hinting was expanded to include more reasonable fallbacks for collections.
Fixes #33

Resolve oneOf discriminator references

---

Bonsai.Sgen.Tests/EnumGenerationTests.cs
Bonsai.Sgen/CSharpNamingConvention.cs

This PR ensures that leading underscores in identifier names are kept in the naming convention, which fixes a relevant edge case when generating enum classes for raw string literals.
Fix #32

Keep leading underscores in generated identifiers

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen.Tests/TestHelper.cs
Bonsai.Sgen/CSharpClassTemplate.cs
Bonsai.Sgen/CSharpCodeDomGenerator.cs
Bonsai.Sgen/CSharpTypeResolver.cs
Bonsai.Sgen/JsonSchemaExtensions.cs
Bonsai.Sgen/Program.cs

This PR expands discriminator inheritance resolution to support deep inheritance hierarchies. It also resolves several complicated assumptions found in NJsonSchema that would limit future support for complex inheritance schemes.
The core of the approach is to resolve `oneOf` inheritance in two passes:
1. for each discriminator schema:
a. if schema is inline, move the discriminator to a separate type definition
b. if the discriminator has `oneOf` declarations, inject the discriminator as `allOf` schema in each of the derived schemas
2. remove discriminator properties from all derived schemas
A simple regression test for a deep inheritance schema is added, but more extensive tests will be required in the future to ensure all edge cases are covered.

Add support for deep oneOf inheritance

---

Bonsai.Sgen/Bonsai.Sgen.csproj
Bonsai.Sgen/Program.cs

This PR extends the `--schema` option to allow specifying the schema path as a URL. This will allow generating serialization resources from online hosted schemas.

Allow specifying the schema path as a URL

---

Bonsai.Sgen/CSharpClassTemplate.cs

This PR tries to fix #46 by modifying the `Required` flag depending on whether the property is nullable or not. It should be noted that this fix is only addressing the JSON generator. I couldn't find documentation on the YAML attributes after looking into the currently used library.

Ensure generated attribute honors nullable & required properties

---

Bonsai.Sgen.Tests/DiscriminatorGenerationTests.cs
Bonsai.Sgen.Tests/TestHelper.cs
Bonsai.Sgen/JsonSchemaExtensions.cs
Bonsai.Sgen/Program.cs

Modern JSON schema uses `$defs` as a standard keyword in schema reference paths. This is unfortunately not yet supported by NJsonSchema (see https://github.com/RicoSuter/NJsonSchema/issues/1536).
As a workaround this PR proposes to resolve the problem by implementing a custom `JsonSchemaVisitor` to add definitions created using `$defs` to the schema.

Allow resolving schema references using $defs keyword

---

Bonsai.Sgen.Tests/PropertyGenerationTests.cs
Bonsai.Sgen/CSharpClassTemplate.cs
Bonsai.Sgen/CSharpClassTemplateModel.cs

Although not strictly mandated by JSON-schema, it is common practice that property default values support arbitrarily nested JSON objects. This PR rearranges the default constructor code generator to support recursive assignment of default values in cases where the default value is an arbitrary JSON object.
It does this by piggybacking on provided JSON schema definitions for the model object properties, and abusing the `ValueGenerator.GetDefaultValue` to obtain valid code snippets for primitive property assignments.
Fixes #41

Allow recursive assignment of default values to complex properties

---

.github/workflows/dotnet.yml
build/Common.props
build/Version.props
src/Bonsai.Sgen.Tests/Bonsai.Sgen.Tests.csproj
src/Bonsai.Sgen.Tests/CompilerTestHelper.cs
src/Bonsai.Sgen/Bonsai.Sgen.csproj

The project target framework is updated to .NET 8. This is the latest long-term support release and will help all CI workflows, as well as the upcoming documentation website generation, to leverage several improvements in this release.
The main required change other than package updates was to have the reference assemblies used in Roslyn-based unit testing to target .NET 8 as well.

Update target framework to .NET 8

---

src/Bonsai.Sgen/Bonsai.Sgen.csproj
src/Bonsai.Sgen/CSharpNamingConvention.cs
src/Bonsai.Sgen/CSharpYamlDiscriminatorTypeInspectorTemplate.cs

The latest version of the YamlDotNet library has introduced breaking changes in interface contracts requiring extra properties to be implemented on custom type inspectors and property descriptors used to implement discriminators for polymorphic class hierarchies.
To make generated code compatible with these changes, which will become mandatory in the upcoming release of the Bonsai editor, we introduce in this PR required modifications to the generated code when targeting YAML serializers.
In general, the changes are actually backwards compatible even in cases where using an old YamlDotNet version, since adding additional properties to classes is non-breaking. The one exception is the [`ReflectionTypeInspector`](https://github.com/aaubry/YamlDotNet/blob/a59301b38b39adc087f55b2d58abe56e34769 …

Update generators to support latest YamlDotNet

---

src/Bonsai.Sgen/CSharpJsonSerializerTemplate.cs

A new property is introduced to allow specifying high-level formatting options. The default formatting remains unindented as before.
Fixes #74

Allow indenting serialized JSON

---

src/Bonsai.Sgen/CSharpClassTemplate.cs
src/Bonsai.Sgen/CSharpCodeDomGenerator.cs
src/Bonsai.Sgen/CSharpSerializerTemplate.cs
src/Bonsai.Sgen/CSharpTypeNameGenerator.cs
src/Bonsai.Sgen/Program.cs

Each schema file must give rise to a distinct namespace due to commonly named operators. Since schema files are often unique and refer to a fully closed set of types, a reasonable default is to use their sanitized name as namespace by default.
The root type name hint will be taken exclusively from the schema title, or from titles in the actual root schema.
A new option `--name | -n` is added to allow explicitly naming the generated file. By default, the generated file name will match the sanitized namespace name.
Fixes #76

Infer namespace from path and type name from title

---

src/Bonsai.Sgen/CSharpCodeDomTemplate.cs
src/Bonsai.Sgen/Program.cs
src/Bonsai.Sgen/SerializerLibraries.cs

To simplify usage we replace serializer options with shorthand flags for JSON and YAML formats. These will point to the appropriate serialization backend for each of the file formats.
The new default is also changed to indicate no serialization. This means the following combinations are now possible:
- `dotnet bonsai.sgen schema.json` (no serializers)
- `dotnet bonsai.sgen schema.json --serializer json` (JSON serializers)
- `dotnet bonsai.sgen schema.json --serializer yaml` (YAML serializers)
- `dotnet bonsai.sgen schema.json --serializer json yaml` (JSON and YAML serializers)

Add shorthand serializer options
